name: Just Build Docker

on:
  pull_request:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Just Build
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ secrets.APP_IMAGE }}
